language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --dev
  - mysql -u root < tests/schema.sql

script:
  - phpunit --coverage-clover tests/coverage-clover.xml

after_success:
  - '[ "$TRAVIS_PHP_VERSION" != "hhvm" ] && vendor/bin/coveralls -v'
